CREATE TABLE BOOKS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(20) NOT NULL,
    title VARCHAR(250) NOT NULL,
    author VARCHAR(250) NOT NULL,
    genre_id INT NOT NULL,
    description VARCHAR(500) NOT NULL,
    quantity INT NOT NULL
);
CREATE TABLE GENRES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);
CREATE TABLE MEMBERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    dob VARCHAR(30) NOT NULL,
    address VARCHAR(250) NOT NULL,
    email VARCHAR(40) NOT NULL,
    join_date VARCHAR(30) NOT NULL
);
CREATE TABLE BORROWS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    book_id INT NOT NULL,
    date VARCHAR(30) NOT NULL,
    end_date VARCHAR(30) NOT NULL
);
